'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const assert = require('node:assert/strict');
process.chdir(path.resolve(__dirname, '..'));
const { version } = require('../package.json');
const build = JSON.parse(fs.readFileSync('release/build-report.json', 'utf8'));
const latest = JSON.parse(fs.readFileSync(`output/playwright/v${version}/latest-isolated-run.json`, 'utf8'));
const qa = JSON.parse(fs.readFileSync(path.join(latest.evidenceDirectory, 'final-qa-report.json'), 'utf8'));
const unit = fs.readFileSync(`output/unit-v${version}.log`, 'utf8');
const tests = Number(unit.match(/# tests (\d+)/)?.[1]);
const passed = Number(unit.match(/# pass (\d+)/)?.[1]);
const failed = Number(unit.match(/# fail (\d+)/)?.[1]);
assert.ok(tests >= 49 && tests === passed && failed === 0, 'Unit tests missing or failing');
assert.equal(qa.passed, true); assert.equal(qa.version, version);
assert.equal(qa.testedZipSha256, build.zipSha256);
assert.equal(qa.externalRequests, 0); assert.equal(qa.consoleErrors.length, 0); assert.equal(qa.failedRequests.length, 0);
assert.ok(qa.mainFlow.ascended && qa.fileCases >= 21 && qa.reducedMotion);
assert.deepEqual(qa.widths, [320,360,390,430,768,1280], 'Final six-width browser matrix incomplete');
if (build.files.some(f => f.path === 'src/audio.js')) assert.ok(qa.extension?.audio?.startsLocked && qa.extension.audio.nineCues && qa.extension.audio.muteAndReload && qa.extension.audio.bands.length === 4, 'Audio acceptance missing');
if (build.files.some(f => f.path === 'src/equipment.js')) assert.ok(qa.extension?.systems?.equipment?.passed && qa.extension.systems.equipment.capacity === 12 && qa.extension.systems.equipment.reloadPreserved && qa.extension.systems.equipment.mortalOnly, 'Equipment acceptance missing');
if (build.files.some(f => f.path === 'src/build.js')) assert.ok(qa.extension?.systems?.build?.passed && qa.extension.systems.build.sources > 0 && qa.extension.systems.build.synergies > 0 && qa.extension.systems.build.readOnly, 'Build acceptance missing');
if (build.files.some(f => f.path === 'src/combat.js')) assert.ok(qa.extension?.systems?.combat?.passed && qa.extension.systems.combat.events >= 4 && qa.extension.systems.combat.skipReadOnly && qa.extension.systems.combat.reloadPreserved && qa.extension.systems.combat.reducedMotion, 'Combat replay acceptance missing');
if (build.files.some(f => f.path === 'src/secret-realm.js')) assert.ok(qa.extension?.systems?.secretRealm?.passed && qa.extension.systems.secretRealm.reloadPreserved && qa.extension.systems.secretRealm.safeExit && qa.extension.systems.secretRealm.mainlinePreserved, 'Secret-realm acceptance missing');
if (build.files.some(f => f.path === 'src/spirit-beast.js')) assert.ok(qa.extension?.systems?.spiritBeast?.passed && qa.extension.systems.spiritBeast.choices === 4 && qa.extension.systems.spiritBeast.oneSlot && qa.extension.systems.spiritBeast.irreversible && qa.extension.systems.spiritBeast.materialSpent && qa.extension.systems.spiritBeast.reloadPreserved && qa.extension.systems.spiritBeast.buildSource && qa.extension.systems.spiritBeast.immortalGate, 'Spirit-beast acceptance missing');
if (build.files.some(f => f.path === 'src/crafting.js')) assert.ok(qa.extension?.systems?.crafting?.passed && qa.extension.systems.crafting.pills === 10 && qa.extension.systems.crafting.materials === 8 && qa.extension.systems.crafting.methods === 3 && qa.extension.systems.crafting.weaponRecipes === 4 && qa.extension.systems.crafting.materialSpent && qa.extension.systems.crafting.buffBounded && qa.extension.systems.crafting.reloadPreserved && qa.extension.systems.crafting.buildSource && qa.extension.systems.crafting.weaponXp, 'Crafting acceptance missing');
if (build.files.some(f => f.path === 'src/karma.js')) assert.ok(qa.extension?.systems?.karma?.passed && qa.extension.systems.karma.activeLimit === 24 && qa.extension.systems.karma.summaryLimit === 40 && qa.extension.systems.karma.sourceTraceable && qa.extension.systems.karma.delayed && qa.extension.systems.karma.settledOnce && qa.extension.systems.karma.reloadPreserved && qa.extension.systems.karma.noRandomPenalty, 'Karma acceptance missing');
const [releaseMajor,releaseMinor] = version.split('.').map(Number);
if(build.files.some(f=>f.path==='src/world.js'))assert.ok(qa.extension?.systems?.world?.passed&&qa.extension.systems.world.parameters===5&&qa.extension.systems.world.eventTypes.length===3&&qa.extension.systems.world.ending&&qa.extension.systems.world.continuation&&qa.extension.systems.world.mortalAndImmortalPreserved&&qa.extension.systems.world.fileCases.length===3,'Creation acceptance missing');
if(build.files.some(f=>f.path==='src/dao.js'))assert.ok(qa.extension?.systems?.dao?.passed&&qa.extension.systems.dao.readOnly&&qa.extension.systems.dao.reloadPreserved&&qa.extension.systems.dao.fileCases.length===3,'Dao acceptance missing');
if(build.files.some(f=>f.path==='src/workbench.js'))assert.ok(qa.extension?.systems?.workbench?.passed&&qa.extension.systems.workbench.meditation&&qa.extension.systems.workbench.mobileNoOverlap,'Workbench acceptance missing');
if (releaseMajor > 1 || releaseMinor >= 11) assert.ok(qa.extension?.systems?.reincarnation?.passed && qa.extension.systems.reincarnation.summary && qa.extension.systems.reincarnation.readOnly && qa.extension.systems.reincarnation.routeHint && qa.extension.systems.reincarnation.noPermanentMultiplier, 'Previous-life echo acceptance missing');
if (build.files.some(f => f.path === 'src/sect.js')) assert.ok(qa.extension?.systems?.sect?.passed && qa.extension.systems.sect.choices === 4 && qa.extension.systems.sect.inheritanceUnlocked && qa.extension.systems.sect.reloadPreserved && qa.extension.systems.sect.leaveClearsEffects, 'Sect acceptance missing');
if (build.files.some(f => f.path === 'src/life.js')) assert.ok(qa.extension?.systems?.life?.passed && qa.extension.systems.life.choices === 3 && qa.extension.systems.life.settledOnce && qa.extension.systems.life.reloadPreserved && qa.extension.systems.life.buildSource && qa.extension.systems.life.refusalAvailable, 'Life-chain acceptance missing');
if (build.files.some(f => f.path === 'src/immortal.js')) assert.ok(qa.extension?.immortal?.passed && qa.extension.immortal.mortalPreserved && qa.extension.immortal.fileCases.length === 3, 'Immortal acceptance missing');
if (build.files.some(f => f.path === 'src/evolution.js')) assert.ok(qa.extension?.evolution?.passed && qa.extension.evolution.largeNumberFixture && qa.extension.evolution.endlessWorlds >= 2 && qa.extension.evolution.fileCases.length === 3, 'Evolution acceptance missing');
let finalSimulation = JSON.parse(fs.readFileSync(`output/final-simulation-v${version}.json`, 'utf8'));
assert.ok(finalSimulation.passed && finalSimulation.simulations === 6000 && finalSimulation.paths.length === 6, 'Final 6000-run simulation missing');
assert.ok(finalSimulation.guarantees.allAscended && finalSimulation.guarantees.allImmortalProloguesComplete && finalSimulation.guarantees.allWormRevengeComplete && finalSimulation.guarantees.memoryTalentSelected, 'Final simulation guarantee failed');
assert.ok(finalSimulation.balanceRatio < 4, 'Final path balance regression');
if (version === '1.0.0') {
  assert.ok(qa.extension?.secondLife?.ledger?.ended === 2 && qa.extension.secondLife.ledger.ascended === 2 && qa.extension.secondLife.memoryTalent?.startsWith('memory-') && qa.extension.secondLife.immortalLaw, 'Second-life browser closure missing');
}
assert.ok(build.zipBytes < 3000000);
for (const f of build.files) assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f.path)).digest('hex'), f.sha256, f.path);
const reviewFile = `docs/REVIEW-v${version}.md`;
assert.ok(fs.existsSync(reviewFile), 'Visual review not yet recorded');
const result = { version, passed: true, zip: build.zip, zipBytes: build.zipBytes, zipSha256: build.zipSha256, unit: { tests, passed, failed }, browser: qa, finalSimulation, review: reviewFile };
fs.writeFileSync(`release/acceptance-v${version}.json`, JSON.stringify(result, null, 2));
fs.writeFileSync(`release/build-report-v${version}.json`, JSON.stringify(build, null, 2));
fs.writeFileSync(`docs/ACCEPTANCE-v${version}.md`, `# v${version} 验收\n\n- 单元测试 ${passed}/${tests}，失败 ${failed}。\n- 凡界完整 DOM 流程：${qa.mainFlow.steps} 次路线循环，seed ${qa.mainFlow.seed}，飞升战力 ${qa.mainFlow.ascendedPower}。\n- 布局检查 ${qa.layoutChecks}，视口 ${qa.widths.join(' / ')}。\n- 文件模式 ${qa.fileCases} 组；减少动态通过；控制台错误、资源失败、外部请求均为 0。\n${finalSimulation ? `- 最终压力仿真：${finalSimulation.simulations} 局，六大道途各 ${finalSimulation.seedsPerPath} 个种子；全部飞升并完成仙界序章与噬灵虫复仇。\n- 第二世真实 DOM：${JSON.stringify(qa.extension.secondLife)}\n` : ''}- 后续专项：${JSON.stringify(qa.extension || null)}\n- ZIP：release/${build.zip}，${build.zipBytes} 字节。\n- SHA-256：${build.zipSha256}\n- 测试证据：${path.relative(process.cwd(), latest.evidenceDirectory).split(path.sep).join('/')}\n- 截图复核：[记录](REVIEW-v${version}.md)。\n\n以上为桌面 Chromium 验证，不替代真机、主观听感、游玩时长与留存评价。\n`);
console.log(JSON.stringify({ version, passed: true, tests, zipBytes: build.zipBytes, zipSha256: build.zipSha256, evidence: latest.evidenceDirectory }, null, 2));
