'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const assert = require('node:assert/strict');
process.chdir(path.resolve(__dirname, '..'));
const { version } = require('../package.json');
const build = JSON.parse(fs.readFileSync('release/build-report.json', 'utf8'));
const latest = JSON.parse(fs.readFileSync(`output/playwright/v${version}/latest-isolated-run.json`, 'utf8'));
const qa = JSON.parse(fs.readFileSync(path.join(latest.evidenceDirectory, 'final-qa-report.json'), 'utf8'));
const unit = fs.readFileSync(`output/unit-v${version}.log`, 'utf8');
const tests = Number(unit.match(/# tests (\d+)/)?.[1]);
const passed = Number(unit.match(/# pass (\d+)/)?.[1]);
const failed = Number(unit.match(/# fail (\d+)/)?.[1]);
assert.ok(tests >= 49 && tests === passed && failed === 0, 'Unit tests missing or failing');
assert.equal(qa.passed, true); assert.equal(qa.version, version);
assert.equal(qa.testedZipSha256, build.zipSha256);
assert.equal(qa.externalRequests, 0); assert.equal(qa.consoleErrors.length, 0); assert.equal(qa.failedRequests.length, 0);
assert.ok(qa.mainFlow.ascended && qa.fileCases >= 21 && qa.reducedMotion);
assert.ok(build.zipBytes < 3000000);
for (const f of build.files) assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f.path)).digest('hex'), f.sha256, f.path);
const reviewFile = `docs/REVIEW-v${version}.md`;
assert.ok(fs.existsSync(reviewFile), 'Visual review not yet recorded');
const result = { version, passed: true, zip: build.zip, zipBytes: build.zipBytes, zipSha256: build.zipSha256, unit: { tests, passed, failed }, browser: qa, review: reviewFile };
fs.writeFileSync(`release/acceptance-v${version}.json`, JSON.stringify(result, null, 2));
fs.writeFileSync(`release/build-report-v${version}.json`, JSON.stringify(build, null, 2));
fs.writeFileSync(`docs/ACCEPTANCE-v${version}.md`, `# v${version} 验收\n\n- 单元测试 ${passed}/${tests}，失败 ${failed}。\n- 凡界完整 DOM 流程：${qa.mainFlow.steps} 次路线循环，seed ${qa.mainFlow.seed}，飞升战力 ${qa.mainFlow.ascendedPower}。\n- 布局检查 ${qa.layoutChecks}，视口 ${qa.widths.join(' / ')}。\n- 文件模式 ${qa.fileCases} 组；减少动态通过；控制台错误、资源失败、外部请求均为 0。\n- 后续专项：${JSON.stringify(qa.extension || null)}\n- ZIP：release/${build.zip}，${build.zipBytes} 字节。\n- SHA-256：${build.zipSha256}\n- 测试证据：${path.relative(process.cwd(), latest.evidenceDirectory).split(path.sep).join('/')}\n- 截图复核：[记录](REVIEW-v${version}.md)。\n\n以上为桌面 Chromium 验证，不替代真机、主观听感、游玩时长与留存评价。\n`);
console.log(JSON.stringify({ version, passed: true, tests, zipBytes: build.zipBytes, zipSha256: build.zipSha256, evidence: latest.evidenceDirectory }, null, 2));
