(function(root,factory){
  const api=factory(typeof module==='object'&&module.exports?require('./journey.js'):root.FSJourney);
  if(typeof module==='object'&&module.exports)module.exports=api;else root.FSJourneyUI=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(J){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const note=t=>`<small>${esc(t)}</small>`;
  function yearCost(s){const E=typeof module==='object'&&module.exports?require('./engine.js'):globalThis.FSEngine;return E.actionPreview(s,'hunt').years;}
  function canSpendYear(s){const E=typeof module==='object'&&module.exports?require('./engine.js'):globalThis.FSEngine;return s.age+E.actionPreview(s,'hunt').years<E.maxAge(s);}
  function blocked(s){const E=typeof module==='object'&&module.exports?require('./engine.js'):globalThis.FSEngine;return s.phase!=='playing'||!!s.immortal||!!s.secretRealm?.active||E.isBlocking(s);}
  function provisions(s,button){const j=s.journey,can=!blocked(s)&&!j.active;
    return `<section class="provisions" aria-label="行前准备"><div class="section-heading"><h3>行前准备</h3><span>带得够，也要回得来</span></div><div class="provision-counts"><span>行粮 <b>${j.supplies}/12</b></span><span>盘缠 <b>${j.silver}</b></span><span>伤药 <b>${j.medicine}</b></span><span>伤势 <b>${j.wounds}/3</b></span></div><div class="preparation-actions">${button('journey-prepare','备六份行粮'+note('6 盘缠'),{id:'supplies',disabled:!can||j.supplies===12||j.silver<6})}${button('journey-prepare','买一份伤药'+note('8 盘缠'),{id:'medicine',disabled:!can||j.medicine===9||j.silver<8})}${button('journey-prepare','敷药疗伤'+note('1 伤药 · 伤势 −2'),{id:'heal',disabled:!can||!j.wounds||!j.medicine})}${button('journey-prepare','留庐静养'+note(yearCost(s)+' 年 · 伤势 −1'),{id:'rest',disabled:!can||!canSpendYear(s)||!j.wounds})}${button('journey-prepare','帮工换盘缠'+note(yearCost(s)+' 年 · 盘缠 +10'),{id:'work',disabled:!can||!canSpendYear(s)||j.silver===9999})}</div></section>`;
  }
  function foundation(s,button){const j=s.journey;if(s.realm>=9||s.immortal)return'';
    if(!j.enabled)return `<aside class="legacy-rules"><span>此世沿用旧版突破规则</span>${button('journey-enable','启用行旅根基',{classes:'text-button',disabled:s.phase!=='playing'})}<small>启用后，突破也需要此境见闻；已有修为和道途保留。</small></aside>`;
    const n=J.required(s.realm),v=j.foundation[s.realm];return `<div class="foundation-line"><div><span>此境根基</span><b>${v} / ${n}</b></div><div class="foundation-marks" aria-label="此境根基 ${v}，需要 ${n}">${Array.from({length:n},(_,i)=>`<i class="${i<v?'filled':''}"></i>`).join('')}</div><p>${v>=n?'阅历已足，静待修为圆满。':'走完一条新路线并成功应对至少两次遭遇，才能留下根基。问道路线所得更多。'}</p>${v<n?button('atlas','去山海寻见闻 →',{ui:true,classes:'text-button'}):''}</div>`;
  }
  function result(j,button){const r=j.last;if(!r)return'';const route=J.ROUTES.find(x=>x.id===r.routeId);return `<section class="journey-result" data-journey-result="${r.ending}"><span class="eyebrow">${r.ending==='complete'?'走完这一程':r.ending==='retreat'?'留得退路':'带伤归来'}</span><h3>${esc(route.name)}</h3><p>${r.ending==='failed'?'暂存所得保留四成。先处理伤势，山路还可以再走。':r.ending==='retreat'?'暂存所得保留八成，没有额外伤势。':'这一程的所得已收入行囊。'}</p><div class="journey-rewards"><span>盘缠 +${r.silver}</span><span>灵材 +${r.materialCount}</span><span>伤药 +${r.medicine}</span><span>根基 +${r.foundation}</span></div>${!r.foundation&&r.ending==='complete'?'<small>同一境界、同一条已掌握路线不重复获得根基；至少两次应对成功才算掌握。</small>':''}${button('practice','回草庐修行',{ui:true,classes:'secondary'})}</section>`;}
  function atlas(s,button,selected='forest',kit='rope'){
    const j=s.journey,region=J.REGIONS.find(r=>r.id===selected)||J.REGIONS[0],locked=region.min>s.realm,unavailable=blocked(s);
    const routes=J.ROUTES.filter(r=>r.region===region.id);
    return `<section class="atlas-view"><header class="page-heading"><span class="eyebrow">行过的路，会长成你的道</span><h2>山海行旅</h2><p>先选去处，再定此行所求。</p></header>${result(j,button)}${unavailable?`<aside class="journey-blocked">先处理当前修行遭遇或完成秘境，再整装出发。${button('practice','回到当前道途 →',{ui:true,classes:'text-button'})}</aside>`:''}<div class="atlas-map" role="group" aria-label="六地山海图"><img src="./assets/art/atlas-v2.1.webp" width="1536" height="1024" alt="黑风林、芦花渡、青石集、断剑山、栖霞故寺与赤砂界隙的水墨舆图">${J.REGIONS.map(r=>`<div class="map-point ${r.id===region.id?'selected':''} ${r.min>s.realm?'locked':''}" style="left:${r.x}%;top:${r.y}%">${button('region',`<i aria-hidden="true"></i><span>${esc(r.name)}</span>`,{ui:true,id:r.id,aria:`查看${r.name}${r.min>s.realm?'，尚未解锁':''}`,pressed:r.id===region.id})}</div>`).join('')}</div><div class="region-tabs" aria-label="地区列表">${J.REGIONS.map(r=>button('region',r.name,{ui:true,id:r.id,pressed:r.id===region.id,classes:r.id===region.id?'selected':''})).join('')}</div><div class="region-heading"><div><span class="eyebrow">${region.subtitle}</span><h3>${region.name}</h3></div><span>${locked?`${['凡人','炼气','筑基','金丹','元婴'][region.min]}起可前往`:`已探 ${j.discoveries.filter(id=>routes.some(r=>r.id===id)).length}/3 条路线`}</span></div><div class="kit-select"><label for="journey-kit">这次随身带</label><select id="journey-kit">${J.KITS.map(k=>`<option value="${k.id}" ${k.id===kit?'selected':''}>${k.name} · ${k.note}</option>`).join('')}</select><small>整装费用 3 盘缠，出发用去 ${yearCost(s)} 年；每段消耗 1～2 行粮。</small></div><div class="route-list">${routes.map((r,i)=>`<article class="route-entry"><span class="route-number">${['一','二','三'][i]}</span><div><h4>${r.name}</h4><p>${r.purpose}</p><small>擅用${{bone:'根骨',mind:'神识',insight:'悟性',luck:'气运'}[r.stat]} · ${r.risk>=8?'险路':r.risk>=4?'需留心':'较平缓'}${j.surveys.includes(`${s.realm}:${r.id}`)?' · 此境已掌握':''}</small></div>${button('journey-start','启程',{id:r.id,kind:kit,classes:'route-start',disabled:unavailable||!canSpendYear(s)||locked||j.supplies<3||j.silver<3||j.wounds>=3})}</article>`).join('')}</div>${unavailable?'<p class="inline-warning">先回修行页处理当前遭遇。飞升后的行旅仍在仙界展开。</p>':''}${!canSpendYear(s)&&s.phase==='playing'?`<p class="journey-blocked">寿元将尽，已无法安排远行。${button('practice','回草庐完成此生 →',{ui:true,classes:'text-button'})}</p>`:''}${provisions(s,button)}<div class="secondary-links">${button('secret-realm','九州旧秘境',{ui:true,classes:'text-button',disabled:unavailable})}${button('act','山野狩猎',{kind:'hunt',classes:'text-button',disabled:unavailable})}<small>旧秘境与山野狩猎仍可寻得器物和吞噬机缘。</small></div></section>`;
  }
  function active(s,button){const j=s.journey,p=J.preview(j),a=j.active;if(!p)return'';
    return `<section class="journey-active"><header class="page-heading"><span class="eyebrow">${p.region.name} / ${p.route.name}</span><h2>${p.scene[0]}</h2><div class="travel-steps" aria-label="行旅进度">${[1,2,3].map(n=>`<span class="${n<=p.step?'visited':''}">${n}</span>`).join('<i></i>')}</div></header><div class="travel-landscape region-${p.region.id}"><img src="./assets/art/atlas-v2.1.webp" alt="${p.region.name}山水" width="1536" height="1024"></div>${a.stepOutcome?`<aside class="step-outcome ${a.stepOutcome.won?'':'is-loss'}" role="status">${esc(a.stepOutcome.title)} · ${a.stepOutcome.won?`应对成功，暂存所得 +${a.stepOutcome.gain}`:`失手，伤势 +${a.stepOutcome.harm}，暂存所得最多损失 2`}。行粮 −${a.stepOutcome.cost}。</aside>`:''}<p class="encounter-prose">${esc(p.scene[1])}</p><div class="travel-status"><span>余粮 <b>${j.supplies}</b></span><span>伤势 <b>${j.wounds}/3</b></span><span>暂存所得 <b>${a.pending}</b></span><span>已应对 <b>${a.successes}/${a.step}</b></span></div><div class="travel-choices">${p.options.map(o=>button('journey-resolve',`<span class="choice-heading"><b>${o.name}</b><strong>${o.chance}%</strong></span><span>${o.note}</span><small>行粮 −${o.cost} · 成功所得 +${Math.round(3*o.gain)} · 失手伤势 +${o.harm}</small>`,{id:o.id,disabled:!o.enabled,classes:'travel-choice'})).join('')}</div><p class="travel-rules">数字为当前成功率；伤势到三层会被迫返回，保留四成所得。行粮不足时可以直接撤回。</p>${button('journey-retreat','收好行囊，撤回草庐'+note('保留八成暂存所得 · 不增加伤势'),{classes:'retreat-button'})}</section>`;
  }
  function hub(s,button,type){const inventory=type==='inventory';
    const groups=inventory?[['随身器物','equipment','本命神兵','查看四槽装备，比较协同与器物成长。'],['丹药与炼制','crafting','丹器百艺','将行旅所得炼成修行和疗伤所需。'],['山中同行','spirit-beast','灵兽仙缘','照看此世结契的灵兽。']]:[['此生命格','journal','此世命册','属性、天命和一路走来的记录。'],['修行之道','build','道途与大道','查看真实协同，元婴之后凝成大道。'],['山门与人间','sect','宗门','入山门、承旧法，也可以继续做散修。'],['身世','life','人生','出身留下的故事与选择。'],['因缘','karma','因果','查看未了之事与它的来处。'],['前尘','legacy','百世回响','历世摘要与下一世的道痕。'],['所见','codex','命途图谱','已经遇见的天命、异变与传说。']];
    return `<section class="hub-view"><header class="page-heading"><span class="eyebrow">${inventory?'行装有轻重，取舍在自己':'只记下此生真正经历的事'}</span><h2>${inventory?'行囊':'人物'}</h2></header>${inventory?provisions(s,button):foundation(s,button)}<div class="hub-list">${groups.map(([label,id,title,text])=>button(id,`<span class="eyebrow">${label}</span><b>${title}</b><span>${text}</span><i aria-hidden="true">→</i>`,{ui:true,classes:'hub-entry'})).join('')}</div></section>`;
  }
  return Object.freeze({provisions,foundation,atlas,active,hub,result});
});
